### ISSUE TITLE
Desktop.Analyzers 1.0.0 not listed, NuGet error causes build to fail in VS 15.3

### ISSUE THREAD

**Issue by tillig** [dotnet/roslyn-analyzers#1286]
-Microsoft.CodeAnalysis.FxCopAnalyzers 1.1.0
-System.Runtime.Analyzers 1.2.0-beta2
-System.Runtime.InteropServices.Analyzers 1.2.0-beta2

The project I'm working on - [Autofac](https://github.com/autofac/Autofac) - has been using this set of analyzers for a while and it's worked fine.

However, with the recent update to VS 15.3 it seems NuGet starts throwing `NU1603` based on Microsoft.CodeAnalysis.Analyzers dependency specifications:

> D:\dev\autofac\Autofac\src\Autofac\Autofac.csproj : error NU1603: Microsoft.CodeAnalysis.FxCopAnalyzers 1.1.0 depends on Desktop.Analyzers (>= 1.0.0 && < 1.2.0) but Desktop.Analyzers 1.0.0 was not found. An approximate best match of Desktop.Analyzers 1.1.0 was resolved. [D:\dev\autofac\Autofac\bench\Autofac.Benchmarks\Autofac.Benchmarks.csproj]
> D:\dev\autofac\Autofac\src\Autofac\Autofac.csproj : error NU1603: Microsoft.CodeAnalysis.FxCopAnalyzers 1.1.0 depends on System.Security.Cryptography.Hashing.Algorithms.Analyzers (>= 1.0.0 && < 1.2.0) but System.Security.Cryptography.Hashing.Algorithms.Analyzers 1.0.0 was not found. An approximate best match of System.Security.Cryptography.Hashing.Algorithms.Analyzers 1.1.0 was resolved. [D:\dev\autofac\Autofac\bench\Autofac.Benchmarks\Autofac.Benchmarks.csproj]

It appears that Desktop.Analyzers 1.0.0 either never existed or was delisted from NuGet. Same for System.Security.Cryptography.Hashing.Algorithms.Analyzers.

Normally I'd rectify this by adding the missing references and manually specifying Desktop.Analyzers 1.1.0 and System.Security.Cryptography.Hashing.Algorithms.Analyzers 1.1.0.

However, after doing that all hell breaks loose. First, I get a false positive that says I should call `GC.SuppressFinalize()` from inside a Dispose method. Easy enough to exclude. The bit I can't exclude is the subsequent set of `MissingMethodException` that get thrown on `ImmutableArray`:

> CSC : error AD0001: Analyzer 'System.Runtime.Analyzers.SpecifyIFormatProviderAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Semantics.IArgument> Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder()'.'.
>  CSC : error AD0001: Analyzer 'System.Runtime.Analyzers.SpecifyIFormatProviderAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Semantics.IArgument> Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder()'.'.
> CSC : error AD0001: Analyzer 'System.Runtime.Analyzers.CallGCSuppressFinalizeCorrectlyAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Semantics.IArgument> Microsoft.CodeAnalysis.Semantics.IInvocationExpression.get_ArgumentsInSourceOrder()'.'.

There are a lot of these, I won't paste them all in.

I've tried updating to the latest versions of the analyzers, but they don't support `netstandard1.1` while we need to keep that support available for our consumers.

Our command line build forces use of `dotnet` SDK 1.0.1. Using just that version of the SDK, the analyzers run and things work peachy. If I force our command line build to use `dotnet` 1.1.0, that's when I start getting this NuGet error. I'm guessing that's part of what I'm hitting when I build from VS.

That said, I can't figure out the magic combination of analyzers that:

- Works in VS 15.3
- Works at the command line using `dotnet` CLI
- Supports `netstandard 1.1` and .NET 4.5

You can see this in action if you just [grab the latest Autofac source, currently at this commit](https://github.com/autofac/Autofac/commit/c5e5cfb38fc5ec363b96e95917b77d86d577c03f) and build from VS 15.3.1.

**Comment by tillig** [comment]
Possibly related, analyzers also display rather oddly in VS 15.3.1. (This is from a different project I'm on that also uses the analyzers and has the same errors I reported above. In this screenshot you'll notice StyleCop is also here. Removing StyleCop does not fix the issue.)

![Analyzers in VS 15.3.1](https://user-images.githubusercontent.com/1156571/29532815-d6d7d5e4-8663-11e7-9678-eeffbb1ae1b6.PNG)

**Comment by mavasani** [comment]
Looks like an issue with the project system, I will port the bug.

**Comment by mavasani** [comment]
There seem to be 2 issues here:

1) 1.1.0 analyzers not working on VS 15.3. This is expected - you should move to 2.3.0-beta1 package of FxCop analyzers.

2. Resources and duplicate Analyzer Utilities node in the solution explorer: Tracked with https://github.com/dotnet/project-system/issues/2724

**Comment by tillig** [comment]
I've lost probably a good day and a half fighting through this. The 1.1.0 analyzers not working on VS 15.3 sounds like something valuable to document on the wiki on this site; in the README.md; and possibly get something posted to [aspnet/Announcements](https://github.com/aspnet/Announcements) - it's really not "obvious stuff" by any means if you're not following the goings-on here on a daily basis.

I'm still working through the right combination of getting this to work from VS and the command line. It appears certain things (like `Microsoft.CodeAnalysis`) get included "automatically" when VS or MSBuild runs the build, but doing straight `dotnet` CLI doesn't so you get errors like

`CSC : error CS8032: An instance of analyzer Microsoft.NetFramework.CSharp.Analyzers.CSharpSpecifyMessageBoxOptionsAnalyzer cannot be created from C:\Users\tillig\.nuget\packages\microsoft.netframework.analyzers\2.3.0-beta1\analyzers\dotnet\cs\Microsoft.NetFramework.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [D:\dev\autofac\Autofac\src\Autofac\Autofac.csproj]`

**Comment by tillig** [comment]
OK, the magic combination, for folks who might get here in the future:

- Use `dotnet` CLI/SDK 1.1.0 or better.
- _Remove_ the references to `System.Runtime.Analyzers` and `System.Runtime.InteropServices.Analyzers`, if you have them.
- Set your references like this:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Net.RoslynDiagnostics" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

The rest of the analyzers get brought in via transitive dependencies.

Note [there's another project bug in 15.3.1](https://github.com/dotnet/project-system/issues/2725) where Roslyn analyzer packages are no longer automatically added with `PrivateAssets` turned on so you have to manually hack the .csproj file to add that node yourself.

**Comment by mavasani** [comment]
Thanks @tillig - I was going to propose something similar. Let me add some documentation on the analyzers repo about the old 1.X.X packages on latest VS bits.

**Comment by mavasani** [comment]
I have added https://github.com/dotnet/roslyn-analyzers/blob/master/README.md#recommended-version-of-analyzer-packages

**Comment by tillig** [comment]
Typo: Version 15.3 corresponds to VS 2017, not VS 2015.

**Comment by mavasani** [comment]
Thanks, for some reason I always mess up the year due to internal code names.
