### ISSUE TITLE
Microsoft.CodeAnalysis.ResxSourceGenerator does not support i18n

### ISSUE THREAD

**Issue by 2A5F** [dotnet/roslyn-analyzers#7041]
### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.ResxSourceGenerator](https://www.nuget.org/packages/Microsoft.CodeAnalysis.ResxSourceGenerator/3.11.0-beta1.23525.2)

**Version**: 3.11.0-beta1.23525.2 (Latest)

### Describe the bug

![image](https://github.com/dotnet/roslyn-analyzers/assets/13982338/38db0a3f-f657-4d2e-8ab5-c1a2837cb7a2)
![image](https://github.com/dotnet/roslyn-analyzers/assets/13982338/76dd8a36-d300-45b4-b708-b5c80217773e)

**Comment by sharwell** [comment]
The analyzers should support localization, and we use it for this in some other repositories. Can you post a sample project where you encountered this problem?

**Comment by 2A5F** [comment]
@sharwell 
https://github.com/2A5F/TestLocalization_for_ResxSourceGenerator

**Comment by sharwell** [comment]
In the sample repository, Microsoft.CodeAnalysis.Analyzers uses version 3.3.4 while Microsoft.CodeAnalysis.ResxSourceGenerator uses 3.11.0-beta1.23525.2. This normally would not be a problem, but there is a bug in Microsoft.CodeAnalysis.Analyzers 3.3.4 that causes it to overwrite the build logic that makes ResxSourceGenerator properly handle culture-specific resources.

**Comment by xPaw** [comment]
I think I am seeing a similar problem in https://github.com/JustArchiNET/ArchiSteamFarm project

I tried the following:
```
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0-beta1.24324.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="3.11.0-beta1.24324.1" />
```

and it still generates `class no-NO` and `class zh-Hant-HK`, producing spammy errors:

```
Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\Strings.Designer.cs(9,33,9,40): error CS0101: The namespace 'ArchiSteamFarm.Localization' already contains a definition for 'Strings'
Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\Strings.no-NO.Designer.cs(11,66,11,83): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
```

Weirldy it only fails to compile in Visual Studio. `dotnet build` works fine.

**Comment by xPaw** [comment]
@sharwell can this issue be reopened?

**Comment by DevSplash** [comment]
> I think I am seeing a similar problem in https://github.com/JustArchiNET/ArchiSteamFarm project
> 
> I tried the following:
> 
> ```
>     <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0-beta1.24324.1" />
>     <PackageVersion Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="3.11.0-beta1.24324.1" />
> ```
> 
> and it still generates `class no-NO` and `class zh-Hant-HK`, producing spammy errors:
> 
> ```
> Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\Strings.Designer.cs(9,33,9,40): error CS0101: The namespace 'ArchiSteamFarm.Localization' already contains a definition for 'Strings'
> Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\Strings.no-NO.Designer.cs(11,66,11,83): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
> ```
> 
> Weirldy it only fails to compile in Visual Studio (version 17.11.2). `dotnet build` works fine.

It also happens in version 17.12.3.

**Comment by xPaw** [comment]
@DevSplash want to open a new issue since this one wasn't reopened?

**Comment by DevSplash** [comment]
https://github.com/dotnet/roslyn-analyzers/issues/7523

**Comment by chr233** [comment]
> https://github.com/dotnet/roslyn-analyzers/issues/7523

这个问题居然这么久了吗

**Comment by DevSplash** [comment]
> > [#7523](https://github.com/dotnet/roslyn-analyzers/issues/7523)
> 
> 这个问题居然这么久了吗

似乎是在.net9版本之后出现的
