### ISSUE TITLE
CA1801 false report for implicit interface implementation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1394]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

ReviewUnusedParameters

#### Repro steps

Open 

#### Expected behavior
No CA1801 for https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs#L42 as it implicitly implements the interface method on IDependency.

#### Actual behavior
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1801	Parameter caption of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	43	Active
Warning	CA1801	Parameter resolved of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	44	Active
Warning	CA1801	Parameter flags of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	45	Active
Warning	CA1801	Parameter schemaName of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	46	Active
Warning	CA1801	Parameter dependencyIDs of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	47	Active
Warning	CA1801	Parameter icon of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	48	Active
Warning	CA1801	Parameter expandedIcon of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	49	Active
Warning	CA1801	Parameter isImplicit of method SetProperties is never used. Remove the parameter or use it in the method body.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	50	Active
```

It seems we do bail out on interface implementation in general cases. For example, no CA1801 is reported on:
```
interface I
{
    void M(int x);
}

class C : I
{
    public void M(int x)
    {
    }
}
```

So likely there is some specific bug in the detection of whether a method is interface implementation,

**Comment by 333fred** [comment]
This is being caused by https://github.com/dotnet/roslyn/issues/15840. We call `FindImplementationForInterfaceMember` on `TestDependency` with the interface `SetProperties` method, and it returns null, so we end up thinking that `TestDependency.SetProperties` does not implement the interface method.

**Comment by AlekseyTs** [comment]
If this issue is caused by #15840, why are we looking at the base class from source and at the derived type from metadata?

**Comment by Youssef1313** [comment]
CA1801 was replaced with IDE0060.

We need to confirm whether IDE0060 has the same bug or not and either move to dotnet/roslyn or close the issue.

**Comment by Youssef1313** [comment]
The line referred to in issue is:

https://github.com/dotnet/project-system/blob/4da0b218c4c655aeafc015f4c699f468d8612c94/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Tree/Dependencies/Snapshot/TestDependency.cs#L42
